version: '3'

services:
  app:
    image: mokkitlink
    container_name: mokkitlink-server-container
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - /root/test-docker/.env:/usr/src/app/.env
      - /etc/letsencrypt:/etc/letsencrypt:ro